### ISSUE TITLE
Missing javafx:javafx:jar:2.1

### ISSUE THREAD

**Issue by col-panic** [canoo/DolphinJumpStart#5]
Just cloned your repo into Eclipse Luna with Java 8, and I get the following problems of missing artifacts

Description	Resource	Path	Location	Type
Missing artifact javafx:javafx:jar:2.1	pom.xml	/client	line 27	Maven Dependency Problem
Missing artifact javafx:javafx:jar:2.1	pom.xml	/combined	line 4	Maven Dependency Problem

thanks!

**Comment by Belkheir** [comment]
Hi mister ,
i'm using java 8 and while compiling one of the jumpstart classes  included in each steps, i got this error :
impossible to load main class step_x.JumpStart

**Comment by Dierk** [comment]
Hi,
how did you compile? Gradle, Maven, IDE, ... ?

**Comment by Belkheir** [comment]
Back, 
Actually i imported  this project as Maven existing Project into Eclipse Luna, and i got this error!

**Comment by Belkheir** [comment]
I compiled this project as Java Application !

**Comment by Dierk** [comment]
Did you use the download?
https://github.com/canoo/DolphinJumpStart/blob/master/dist/jumpstart-maven.zip?raw=true

**Comment by Belkheir** [comment]
Yes i extract the project from jumstart-maven.zip 
![image](https://cloud.githubusercontent.com/assets/11693341/7339223/867dee34-ec56-11e4-92d7-36f536aeaad8.png)

**Comment by Belkheir** [comment]
i just have fixed the problem ,the projet is working well ! thank you Mr Dierk ;)

**Comment by Dierk** [comment]
Super, Have fun!
Dierk
